import { DEMO_USER } from "./demo"

export const demoFichas = [
  {
    id: "demo-1",
    user_id: DEMO_USER.id,
    tipo: "cliente" as const,
    nombre: "María García",
    ruc: "1792345678001",
    telefono: "+593 99 123 4567",
    email: "maria.garcia@empresa.ec",
    relacion: "cliente" as const,
    campos_personalizados: {},
    etapa_ventas: "Ganado",
    etapa_postventa: null,
    creado_at: new Date().toISOString(),
    actualizado_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    user_id: DEMO_USER.id,
    tipo: "prospecto" as const,
    nombre: "Carlos López",
    ruc: "1804567892001",
    telefono: "+593 98 234 5678",
    email: "carlos.lopez@empresa.ec",
    relacion: "lead" as const,
    campos_personalizados: {},
    etapa_ventas: "Propuesta",
    etapa_postventa: null,
    creado_at: new Date(Date.now() - 86400000).toISOString(),
    actualizado_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    user_id: DEMO_USER.id,
    tipo: "prospecto" as const,
    nombre: "Ana Martínez",
    ruc: null,
    telefono: "+593 97 345 6789",
    email: "ana.martinez@gmail.com",
    relacion: "lead" as const,
    campos_personalizados: {},
    etapa_ventas: "Conversación",
    etapa_postventa: null,
    creado_at: new Date(Date.now() - 172800000).toISOString(),
    actualizado_at: new Date().toISOString(),
  },
  {
    id: "demo-4",
    user_id: DEMO_USER.id,
    tipo: "cliente" as const,
    nombre: "Roberto Sánchez",
    ruc: "1712345678001",
    telefono: "+593 96 456 7890",
    email: "roberto.sanchez@empresa.ec",
    relacion: "cliente" as const,
    campos_personalizados: {},
    etapa_ventas: null,
    etapa_postventa: "En Proceso",
    creado_at: new Date(Date.now() - 259200000).toISOString(),
    actualizado_at: new Date().toISOString(),
  },
]

export const demoTasks = [
  {
    id: "task-1",
    user_id: DEMO_USER.id,
    ficha_id: "demo-1",
    title: "Enviar propuesta comercial",
    description: "Preparar y enviar la propuesta a María García",
    priority: "high" as const,
    status: "pending" as const,
    due_date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    due_time: null,
    created_at: new Date().toISOString(),
    completed_at: null,
  },
  {
    id: "task-2",
    user_id: DEMO_USER.id,
    ficha_id: "demo-2",
    title: "Llamada de seguimiento",
    description: "Confirmar interés del cliente",
    priority: "normal" as const,
    status: "completed" as const,
    due_date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    due_time: null,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    completed_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "task-3",
    user_id: DEMO_USER.id,
    ficha_id: null,
    title: "Revisar métricas del mes",
    description: "Analizar KPIs de ventas",
    priority: "normal" as const,
    status: "pending" as const,
    due_date: new Date(Date.now() + 259200000).toISOString().split("T")[0],
    due_time: null,
    created_at: new Date().toISOString(),
    completed_at: null,
  },
]

export const demoKanbanColumns = {
  ventas: [
    { id: "col-1", user_id: DEMO_USER.id, tipo: "ventas", nombre: "Por Contactar", posicion: 0, color: "#6366f1" },
    { id: "col-2", user_id: DEMO_USER.id, tipo: "ventas", nombre: "Conversación", posicion: 1, color: "#8b5cf6" },
    { id: "col-3", user_id: DEMO_USER.id, tipo: "ventas", nombre: "Propuesta", posicion: 2, color: "#f59e0b" },
    { id: "col-4", user_id: DEMO_USER.id, tipo: "ventas", nombre: "Ganado", posicion: 3, color: "#10b981" },
  ],
  postventa: [
    { id: "col-5", user_id: DEMO_USER.id, tipo: "postventa", nombre: "Onboarding", posicion: 0, color: "#3b82f6" },
    { id: "col-6", user_id: DEMO_USER.id, tipo: "postventa", nombre: "En Proceso", posicion: 1, color: "#8b5cf6" },
    { id: "col-7", user_id: DEMO_USER.id, tipo: "postventa", nombre: "Por Facturar", posicion: 2, color: "#f59e0b" },
    { id: "col-8", user_id: DEMO_USER.id, tipo: "postventa", nombre: "Archivado", posicion: 3, color: "#6b7280" },
  ],
}

export const demoTimeline = [
  {
    id: "tl-1",
    ficha_id: "demo-1",
    user_id: DEMO_USER.id,
    tipo: "llamada",
    titulo: "Llamada inicial",
    contenido: "Contacto inicial con María para presentar servicios",
    fecha: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "tl-2",
    ficha_id: "demo-1",
    user_id: DEMO_USER.id,
    tipo: "nota",
    titulo: "Reunión programada",
    contenido: "Programar reunión para la próxima semana",
    fecha: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "tl-3",
    ficha_id: "demo-2",
    user_id: DEMO_USER.id,
    tipo: "email",
    titulo: "Envío de propuesta",
    contenido: "Se envió propuesta comercial por email",
    fecha: new Date(Date.now() - 86400000).toISOString(),
  },
]

export function getDemoStats() {
  return {
    totalFichas: demoFichas.length,
    totalClientes: demoFichas.filter(f => f.tipo === "cliente").length,
    totalProspectos: demoFichas.filter(f => f.tipo === "prospecto").length,
    tareasPendientes: demoTasks.filter(t => t.status === "pending").length,
    tareasAltaprioridad: demoTasks.filter(t => t.priority === "high" && t.status === "pending").length,
  }
}
